services:
  llama-server:
    depends_on:
      - mcp-proxy

  mcp-proxy:
    image: local/mcp-proxy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/sparfenyuk/mcp-proxy:latest
        RUN python3 -m ensurepip && pip install --no-cache-dir uv
        ENV PATH="/usr/local/bin:$$PATH" \
            UV_PYTHON_PREFERENCE=only-system
        ENTRYPOINT ["catatonit", "--", "mcp-proxy"]
    container_name: mcp-proxy
    ports:
      - "8096:8096"
    command: >
      --pass-environment --port=8096 --host 0.0.0.0 --named-server-config /app/mcp_config.json --allow-origin "*" --stateless
    volumes:
      - ../configs/mcp_config.json:/app/mcp_config.json
